### ISSUE TITLE
Reading Microprofessor MPF-1 format tape cassettes

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [eightbitjim/cassette-nibbler#43]
The Microprofessor MPF-1 [https://en.wikipedia.org/wiki/Micro-Professor_MPF-I](url) is a popular single board computer from the 80s. I am looking for a way to retrieve my old software from cassette tapes. I've found a GitHub project [https://github.com/Glitchbone/data2mpf](url) for **writing** a Microprofessor WAV file but no WAV reader. 
Maybe cassette-nibbler comes to the rescue. But so far I could not find out where the tape format description for the various platforms you are supporting is hiding. I've checked `\Cassettecassettenibbler\Platforms\Sinclair` but could not even find the pulse frequencies used.
```C
 ZX Spectrum Tape format:
      ┌────────┐        ┌────────┐        ┌─┐┌──┐  ┌──┐  ┌──────┐      ┌
   ...┘        └────────┘        └────────┘ └┘  └──┘  └──┘      └──────┘

              807 Hz            807 Hz       1022 Hz 1022 Hz  2044 Hz
       <────────────────><────────────────><><─────><────><────────────>
          Leader tone (last 2 impulses)  "Sync" "0"   "0"       "1"
```
I've attached the MPF tape data format for your reference [MPF-1 Tape data format.pdf](https://github.com/eightbitjim/cassette-nibbler/files/2599267/MPF-1.Tape.data.format.pdf)
Maybe I'm able to add the MPF tape data format myself once I understand better...

**Comment by eightbitjim** [comment]
I am happy to have a go at adding the format, but unfortunately can't pick it up for a few days. 

If you want to have a look yourself, the format looks similar to the Acorn Byte format, in that there is a start bit and a stop bit on each byte frame, and the bits themselves are made up of more than one cycle.

If you look in Platforms/Acorn/PulseExtraction/AcornPulseExtractor, you can see the length of the short and long "pulses" (in nanoseconds-- eek!). A pulse is half a cycle. The Pulse Extractor labels the incoming cycles as "short" and "long". It also deals with the leader tone, adjusting the frequency it is expecting for short and long pulses if the tape is running slightly the wrong speed.

Each pulse is passed to Platforms/Acorn/FileExtraction/AcornByte to start to build a byte. addPulse() assembles the pulses into zero and one bits. processBit() also passes the bits to ddBitToByte() to assemble the byte frames. addPulse() finally returns either a completed byte value, or MORE_BITS_NEEDED or an error.

I think I'll probably add a generic format that is easily tweak-able, so people don't have to get their heads around all this if all you are looking for is a stream of bytes.

**Comment by ThomasHeinrichSchmidt** [comment]
I've tried to use a configuration for the automatic platform, like this
```C
Java -jar target/cassette-nibbler-0.2.jar -platform=automatic -config=ssssssssmm-ssssmmmm-18-a-22-44-1000 -logging=parsing   output.wav 
```
This did not work out so far, probably because I cannot specify start and stop bits as you explain above.
I'm also not sure what the unit is for the (short/medium/long) pulses in the configuration, is it also in nanoseconds-- eek?

BTW: I had to modify `cassette-nibbler\src\test\java\com\eightbitjim\cassettenibbler\Platforms\Acorn\FileExtraction\BBCFileTest.java` to pass the (build) test (I did simply ignore the test using `assertTrue("ASCII data hash incorrect: " + hash + " (expected: " + expectedStringHash + ")", hash == hash);  // ignore for now`). 
I'm on Windows, and the build gives me a  `[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!`

**Comment by eightbitjim** [comment]
Thanks for the tip about building on Windows. I'll look at that.

Looks like you're taking the right approach with the "automatic" platform. The results are very variable, but I'm hopeful I can tweak it to work when I pick this up. 

It looks like the units for the short/medium/long pulses for the automatic encoding scheme are multiples of 25000ns, but I need to go and confirm that as I never really checked the values-- the idea was that it should determine them itself. One option is to just run it in automatic mode with no configuration on an audio file that just contains your tape data, and see what numbers it eventually suggests (if any), then supply the rest of the configuration yourself. When I run it over a Spectrum file, it comes up with pulse lengths 67, 135 and 166.

Also, it might be worth trying inverting the signal (-invert, or just supply a second file inverted), as this impacts the length of a complete cycle when it transitions between short/long if it's expecting it the other way up.

Anyway, hope that helps. I'll pick this up in a few days and make some tweaks if needed, perhaps sorting out the units to something more meaningful. Thanks for trying.

**Comment by ThomasHeinrichSchmidt** [comment]
I appreciate your help very much and look forward to you adding the format. I'll go ahead then and start recording the rest of the tapes that are still around. I'll attach one of the recordings for your reference:
[output.zip](https://github.com/eightbitjim/cassette-nibbler/files/2601323/output.zip)

**Comment by eightbitjim** [comment]
I've created a new branch (add-mpf1) and added an early version that reads something out of the file you supplied. I recommend running with the -platform=mpf1 option. Currently early days, in that it doesn't read the checksum and won't deal very well with errors. It just appends the data to the header and outputs three identical files (.bin, .TAP and .txt all have the same binary data).

I'm also not convinced I'm reading the header correctly; it implies to me that there should be more data in the file. Will check this tomorrow!

**Comment by ThomasHeinrichSchmidt** [comment]
The output.wav from my zip has filename 0x1234 and the following data (see project [data2mpf](https://github.com/Glitchbone/data2mpf))
```
00001800: DD 21 20 18 CD FE 05 FE 13 20 F9 76 00 00 00 00    ]!..M~.~..yv....
00001810: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
00001820: AE B5 1F 85 8F 37                                  .5...7 
```
This file has been generated by the software (ie. more easy to read).
I enclose another file which I actually read from one of my casettes yesterday. The first program on this WAV recording has file name 0x4B82 and the following data:
```
00001e00: 31 AF 1F CD FE 05 F5 2A DE 1F FE 16 28 1C FE 17    1/.M~.u*^.~.(.~.
00001e10: 28 17 FE 12 20 07 3A E4 1F FE 04 28 22 F1 CD E9    (.~...:d.~.("qMi
00001e20: 00 21 2F 00 CD E2 05 18 D7 37 23 22 AF 1F 23 30    .!/.Mb..W7#"/.#0
00001e30: 02 2B 2B 22 B3 1F 29 22 B1 1F CD E5 03 20 DE 21    .++"3.)"1.Me..^!
00001e40: AF 1F CD 3D 05 38 D6 21 ED 1F 36 01 CD 55 1E 34    /.M=.8V!m.6.MU.4
00001e50: CD 55 1E 18 C8 E5 21 00 18 01 00 1E 3A B0 1F FE    MU..He!.....:0.~
00001e60: 1E 38 07 26 20 BC 38 0F 06 28 18 01 09 C5 CD 8F    .8.&.<8..(...EM.
00001e70: 1E C1 B7 ED 42 38 F5 E1 C9 30 12 E5 CD 1E 1F 19    .A7mB8uaI0.eM...
00001e80: EB E1 3A ED 1F FE 02 20 04 72 2B 73 23 23 C9 EB    ka:m.~...r+s##Ik
00001e90: 1A 21 3F 1F 22 EE 1F 2E 4D FF 30 0A EB 23 5E 23    .!?."n..M.0.k#^#
00001ea0: 56 CD 2E 1F 18 D3 FF 30 07 62 6B CD 2E 1F 18 34    VM...S.0.bkM...4
00001eb0: FF 38 2C FF 38 2A 13 FE DD 28 04 FE FD 20 17 1A    .8,.8*.~](.~}...
00001ec0: FE DD 20 02 19 C9 FF 38 16 FE 39 28 14 FE 34 38    ~]...I.8.~9(.~48
00001ed0: 10 FE BF 38 0B 13 FE ED 20 08 1A FF FF 30 02 13    .~?8..~m.....0..
00001ee0: 13 13 EB C9 CB 19 23 7E CB 7F 28 01 15 83 5F 30    ..kIK.#~K.(..._0
00001ef0: 01 14 13 13 CD 2E 1F CB 79 30 03 28 03 AF 28 1C    ....M..Ky0.(./(.
00001f00: E5 CD 1E 1F 19 D1 13 B7 ED 52 7D 17 7C CE 00 C2    eM...Q.7mR}.|N.B
00001f10: 53 03 EB 2B 3A ED 1F FE 02 20 01 73 23 C9 D5 2A    S.k+:m.~...s#IU*
00001f20: B3 1F ED 5B AF 1F 38 01 EB B7 ED 52 D1 C9 E5 2A    3.m[/.8.k7mRQIe*
00001f30: B1 1F B7 ED 52 3F 30 05 2A AF 1F ED 52 E1 C9 B7    1.7mR?0.*/.mRaI7
00001f40: 06 00 4E 23 ED A1 20 01 37 EA 44 1F C9 12 C2 C3    ..N#m!..7jD.I.BC
00001f50: C4 CA CC CD D2 D4 DA DC E2 E4 EA EC F2 F4 FA FC    DJLMRTZ\bdjlrtz|
00001f60: 06 10 18 20 28 30 38 08 01 11 21 22 2A 31 32 3A    ....(08...!"*12:
00001f70: 11 06 0E 16 1E 26 2E 36 3E C6 CB CE D6 DE E6 EE    .....&.6>FKNV^fn
00001f80: F6 FE 05 21 22 2A 36 CB 06 43 4B 53 5B 73 7B       v~.!"*6K.CKS[s{ 
```
[1.zip](https://github.com/eightbitjim/cassette-nibbler/files/2611667/1.zip)

**Comment by eightbitjim** [comment]
Ha, yes thank you I was doing that incorrectly. After receiving a byte frame I was reading the wrong bits out to form the byte (I was including the start bit as part of the byte). When I run it on your 1.zip I seem to get the same output.

**Comment by ThomasHeinrichSchmidt** [comment]
Fetched, built, and run your new branch `add-mpf1` using: 
```
java -jar target/cassette-nibbler-0.3.jar -platform=mpfi 1.wav
```
all went well, I received all the files I expected + some more (I have to check on those :).
From my point of view, the issue can be closed as successfully completed.
I thank you very much for your good work and wish you every success in all your efforts.

**Comment by eightbitjim** [comment]
Great, glad that worked. I'll merge this back into the main branch.
